version: '3'

services:
  web:
    command: yarn start

  chrome:
    image: medology/seleniarm-standalone-chromium:4.1.3-20220412
    ports:
      - "5900:5900"
      - "7900:7900"
    healthcheck:
      test: ["CMD", "wget", "localhost:4444", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - web
    environment:
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1200
    shm_size: 2g
